Step3 - GitHub(UI)
next-step/android-github pull request #88
Opened 2023-02-26 11:43 UTC by poytok

안녕하세요 리뷰어님

Hilt 사용해서 의존성 주입을 했는데 app 모듈에서 data 모듈의 의존 없이 Repository을 주입을 하는 방법을 잘 모르겠어서 의존성을 추가하고 진행하였습니다

감사합니다.

2023-02-26 17:19 UTC, AnKyungMoo requested changes
전체적으로 과제를 깔끔하게 잘 진행해주셨네요!!
마지막 과제인 만큼 조금 더 수정해보면 좋을 것 같아서 코멘트 드렸습니다!

추가적으로 현재 빌드가 깨지고있네요ㅠㅠ
같이 수정해보시면 좋을 것 같습니다!

2023-02-26 17:19 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/github/MainActivity.kt
> +    val githubAdapter: GitHubRepositoryInfoAdapter by lazy { GitHubRepositoryInfoAdapter() }
lazy를 이용하여 지연초기화를 진행한 이유가 있나요!?

2023-02-26 17:19 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/github/MainViewModel.kt
> +    val githubRepositoryInfoLiveData: LiveData<List<GitHubRepositoryInfo>> get() = _githubRepositoryInfoLiveData
backing property를 이용하여 캡슐화를 진행해 준 것 너무 좋습니다 👍 👍 
다만 변수명에 타입을 적어주는 것은 장점보단 단점을 많이 갖게 됩니다.

만약 이 LiveData의 타입을 Flow로 변경하게 된다면 변수명도 같이 변경되어야한다는 단점이 있습니다.
또한 이 변수가 LiveData인지 변수명을 통해 타입을 알아야할 이유가 있을까요?!
따라서 githubRepositoryInfo까지만 사용해주는 것이 오히려 명확한 명명이라고 생각됩니다~

2023-02-26 17:19 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/github/MainViewModel.kt
> +    }
뷰에서 버튼을 통해 깃허브 레포지토리 정보를 가져오는 것을 갱신하는 로직이 생긴다면 어떻게 해야할까요?
해당 함수는 private으로 뷰모델 내에서 실행하기보단, 외부에서 사용할 수 있는 환경을 만들어주는 것이 더욱 어울린다고 생각됩니다.
또한 이번 요구사항에서는 해당 함수의 호출 위치가 정해지진 않았지만, 뷰모델의 init 시점에 호출되는 것보다는 뷰단에서 실행되도록 변경하는 것이 좋을 것 같습니다.

2023-02-26 17:19 UTC, AnKyungMoo commented on app/src/main/res/layout/activity_main.xml
> +            android:adapter="@{view.githubAdapter}"
Activity에서 같은 역할을 수행할 수 있기 때문에 Activity는 xml이 알고 있을 필요가 없습니다..!
adapter를 가져오기 위함이라면 adapter만 변수로 넘기는 것이 더 좋아보이네요~

저의 경우 adapter는 그냥 activity에서 바인딩 해주는 편입니다.
이 부분은 취향따라 진행해주세요~

2023-02-26 17:19 UTC, AnKyungMoo commented on app/src/test/java/camp/nextstep/edu/github/MainViewModelTest.kt
> +//class MainViewModelTest {
이 테스트 클래스를 주석처리하신 이유가 있을까용??

2023-02-26 17:19 UTC, AnKyungMoo commented on data/build.gradle.kts
> +    kapt( "com.google.dagger:hilt-compiler:2.45")
```suggestion
    implementation("com.google.dagger:hilt-core:2.45")
    kapt("com.google.dagger:hilt-compiler:2.45")
```

Nit: 공백이 들어가있네요 😅😅

2023-02-26 17:20 UTC, AnKyungMoo commented on app/src/test/java/camp/nextstep/edu/github/MainViewModelTest.kt
> +//class MainViewModelTest {
이유를 작성해주셨었네요..! 저도 확인 다시 해보겠습니다!

2023-02-26 17:24 UTC, AnKyungMoo commented
> Hilt 사용해서 의존성 주입을 했는데 app 모듈에서 data 모듈의 의존 없이 Repository을 주입을 하는 방법을 잘 모르겠어서 의존성을 추가하고 진행하였습니다

app 모듈에서 data 모듈의 의존성 가져가는 것이 맞습니다 :) 잘 진행해주셨어요
internal로 모듈 내 클래스들을 접근할 수 없게 만들었기 때문에 이슈 없습니다!

2023-03-02 01:10 UTC, poytok commented on app/src/main/java/camp/nextstep/edu/github/MainActivity.kt
> +    val githubAdapter: GitHubRepositoryInfoAdapter by lazy { GitHubRepositoryInfoAdapter() }
DataBinding으로 활용하기 위해서 사용했습니다

2023-03-02 10:14 UTC, AnKyungMoo requested changes
질문 주셨던 ViewModelTest 관련으로 답변 남겨두었어요!
전체적으로 너무 잘 반영해주셨는데요~ 해당 부분은 확인해야 할 것 같아서 한 번 더 request 드렸습니다.
해당 부분 확인해보시고 다시 pr 요청해주시면 감사하겠습니다 :)

2023-03-02 10:14 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/github/MainActivity.kt
> +    private lateinit var githubAdapter: GitHubRepositoryInfoAdapter
Nit: lateinit이어야하는 이유가 특별하게 없을 때는 바로 선언해주는 것도 좋아요~
val로 선언할 수 있다면 불변객체의 장점을 가질 수 있기 때문입니다..!

```suggestion
    private val githubAdapter: GitHubRepositoryInfoAdapter = GitHubRepositoryInfoAdapter()
```

2023-03-02 10:14 UTC, AnKyungMoo commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_height="match_parent"
ConstraintLayout을 사용하는 경우 match_parent를 이용하는 것 보단 match_constraint를 이용하는 것을 권장드려요~

참고: https://developer.android.com/develop/ui/views/layout/constraint-layout#adjust-the-view-size

2023-03-02 10:14 UTC, AnKyungMoo commented on app/src/test/java/camp/nextstep/edu/github/MainViewModelTest.kt
> +    }
위 테스트함수는 repository의 기능을 테스트를 하는 테스트가 되었는데요~
이미 data module에서 해당 테스트를 진행하고 있기 때문에 ViewModelTest에서 수행해야하는 테스트가 아니라고 보여지네요..!
현재 repository에서 오는 타입이 한가지로 정해져있는데요. 이 경우에는 특별히 뷰모델 테스트코드가 필요하다라고 판단되어지지는 않습니다.

간단한 예시를 들어보자면, repository를 통하여 api를 호출했을 때 api 호출 성공, 실패를 판단할 수 있도록 결과를 wrapping 하는 경우가 있습니다. (보통 이런 경우 UseCase라는 단위를 새로 만들어서 진행합니다.) 성공이 왔을 때와, 실패가 왔을 때 **뷰에 보내야할 데이터나 동작 등을 테스트해주는 것**이 뷰모델 테스트의 목적에 맞춰서 진행하는 것이라고 볼 수 있겠네요.
참고할만한 글) https://medium.com/adidoescode/android-arch-exploration-mvvm-flow-usecases-with-a-ui-gate-combine-use-cases-output-to-541abc6a7b8c (The repository의 Outcome 부분 보시면 좋습니다.)

이런경우에는 자연스럽게 실제 repository를 주입받기보다는 mock객체를 만들어서 수행하게되겠네요..!

결과적으로는 현재 코드에서는 해당 뷰모델 테스트는 존재하지 않는 것이 더욱 좋습니다!

2023-03-03 08:25 UTC, poytok commented on app/src/test/java/camp/nextstep/edu/github/MainViewModelTest.kt
> +    }
hilt를 썼으니 inject테스트 겸 해야되나, mock으로 해야되나 고민했었는데 설명해주셔서 감사합니다!

저도 테스트하면서 Repository 테스트랑 동일한 테스트인거 같은데 이게 맞나 싶기도 했는데 완전 잘 이해됐습니다 감사합니다!!

2023-03-03 08:31 UTC, poytok commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_height="match_parent"
0dp를 match_constraint라고 하는걸 처음 알았습니다!

2023-03-03 11:35 UTC, AnKyungMoo approved these changes
github 과제 진행하시느라 고생 많았습니다!
질문해주신 부분들을 보며 저도 더 고민해볼 수 있는 기회가 되었던 것 같습니다 :)
이번 미션은 마무리하도록 할게요~!

2023-03-03 11:36 UTC, merged