feat: 3단계 git hub (UI)
next-step/android-github pull request #95
Opened 2023-03-05 14:48 UTC by hj1115hj

마지막 까지 잘부탁 드립니다~ hilt 신기하네요~

2023-03-06 14:05 UTC, wisemuji approved these changes
안녕하세요 혜진님!

3단계 구현을 잘 해주셨습니다 💯  마지막까지 깔끔한 구현이 좋았습니다
고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다.

지금도 충분히 구현을 잘 해주셔서 아마 다음 리뷰 요청에서는 머지하지 않을까 싶습니다 🙂

2023-03-06 14:05 UTC, wisemuji commented on app/build.gradle.kts
> +    implementation(project(mapOf("path" to ":data")))
위에서 정의해줬기 때문에 이 구문은 빼도 됩니다!

2023-03-06 14:05 UTC, wisemuji commented on app/src/main/java/camp/nextstep/edu/github/GithubApplication.kt
> +class GithubApplication : Application()
Application 클래스에 Hilt 초기화 👍

2023-03-06 14:05 UTC, wisemuji commented on app/src/main/java/camp/nextstep/edu/github/MainActivity.kt
> +    }
binding을 다루는 로직과 searchRepositories를 호출하는 로직도 함수로 분리해보면 어떨까요?

2023-03-06 14:05 UTC, wisemuji commented on app/src/main/java/camp/nextstep/edu/github/MainActivity.kt
> +        binding.rvSearchResult.apply {
scope 함수의 리턴 값을 사용하지 않는다면 with를 사용해보는걸 고려해볼 수 있습니다. 어던 차이가 있을까요?

2023-03-06 14:05 UTC, wisemuji commented on app/src/main/java/camp/nextstep/edu/github/MainViewModel.kt
> +    fun searchRepositories() = viewModelScope.launch(Dispatchers.IO) {
참고로 Retrofit은 내부에서 비동기 처리를 해주고 있기 때문에 Dispatcher를 굳이 명시하지 않아도 됩니다 🙂

2023-03-06 14:05 UTC, wisemuji commented on app/src/main/java/camp/nextstep/edu/github/MainViewModelFactory.kt
> +            MainViewModel(searchRepository) as T
> Unchecked cast: MainViewModel to T
마지막 PR인만큼 Github Action에서 check warning이 뜨는 부분을 해결해보는걸 목표로 해보면 어떨까요~?

2023-03-06 14:05 UTC, wisemuji commented on app/src/main/java/camp/nextstep/edu/github/MainViewModelFactory.kt
> +    }
depth를 최대한 줄이고 싶다면 같은 역할을 하는 구문을 다음처럼 작성할 수도 있습니다! 이 피드백은 참고만 해주세요 🙂 
```suggestion
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        require(modelClass.isAssignableFrom(MainViewModel::class.java)
        return MainViewModel(searchRepository) as T
    }
```

2023-03-06 14:05 UTC, wisemuji commented on data/src/main/java/camp/nextstep/edu/github/data/di/NetworkModule.kt
> +object NetworkModule {
DI를 활용해 잘 구현해주셨어요 👍

2023-03-06 14:05 UTC, wisemuji commented on data/src/main/java/camp/nextstep/edu/github/data/model/RepositoryEntity.kt
> +data class RepositoryEntity(
data 모듈은 domain 모듈에 의존하지만 domain은 data를 알지 못하도록 잘 구현해주셨네요 👍

2023-03-06 14:06 UTC, wisemuji requested changes
안녕하세요 혜진님!

3단계 구현을 잘 해주셨습니다 💯 마지막까지 깔끔한 구현이 좋았습니다
고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다.

지금도 충분히 구현을 잘 해주셔서 아마 다음 리뷰 요청에서는 머지하지 않을까 싶습니다 🙂

2023-03-06 14:06 UTC, wisemuji commented
(실수로 request changes가 아닌 approve를 해버려서 불가피하게 다시 코멘트 남깁니다 😓 )

2023-03-12 10:15 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/github/MainViewModel.kt
> +    fun searchRepositories() = viewModelScope.launch(Dispatchers.IO) {
신기하네요~ 정보 감사합니다 :)

2023-03-12 10:16 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/github/MainViewModelFactory.kt
> +    }
require 쓰임새가 유용하네요~ 감사합니다! :)

2023-03-12 10:21 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/github/MainActivity.kt
> +        binding.rvSearchResult.apply {
with은 scope함수 반환을 하지 않아서 단순 수신객체를 반복해서 코드 작성해야하는 경우에 사용하는게 적절한것 같습니다.  apply는 수신객체를 반환하기 떄문에 초기화 후 수신객체를 사용할때 사용하는게 적절해 보여요.

2023-03-12 10:41 UTC, hj1115hj commented
수정이 늦었어요 수강 기한 끝나구 리뷰올리기 되어 죄송합니다! 시간 나실 때 리뷰 주시면 감사하겠습니다 :)

2023-03-14 02:13 UTC, wisemuji approved these changes
안녕하세요 혜진님! 깔끔하게 리뷰 반영을 잘 해주셨습니다 💯 

3단계동안 고생 많으셨습니다. 마지막까지 완주하신 게 인상적이였습니다.
완주까지 얼마 남지 않으셨네요! 남은 미션도 응원하겠습니다 🙏

2023-03-14 02:13 UTC, wisemuji commented on data/src/main/java/camp/nextstep/edu/github/data/model/RepositoryEntity.kt
> +    }
이러한 매핑 코드를 다음과 같이 매퍼로 분리하여 관리할 수도 있습니다.
이렇게 매퍼 클래스를 따로 만들게 되면 데이터를 가공하는 역할과 책임을 더욱 잘 분리할 수 있고 인터페이스 형태로 관리하여 프로그램 전반의 코딩 스타일을 통일할 수 있습니다. 어떤 방법이 좋을지는 스스로 고민해보고 찾아보시면 도움이 될 거예요!
```kotlin
class RepositoryMapper : Mapper<RepositoryEntity, Repository> {

    override fun toDomain(entity: RepositoryEntity): Repository =
        Repository(
            fullName = entity.fullName,
            description = entity.description
        )

    override fun toEntity(domain: Repository): RepositoryEntity =
        RepositoryEntity(
            fullName = domain.fullName,
            description = domain.description
        )
}
```

2023-03-14 02:13 UTC, merged